# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
